dist: bionic
language: d

d: ldc

install:
  - dub --version
  - python --version
  - pip install --user lit
  - python -c "import lit; lit.main();" --version | head -n 1
  - llvm-config --version

script:
  - make LLtool
  - ./LLtool -h
  - make examples
  - make FileCheck
  - make runtest
